config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'residents#new'
  resources :residents do
    member do
      patch 'update_status'
    end
  end
  resources :search, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :resident

  validates :zip_code, :street, :neighborhood, :city, :state, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resident.rb
# frozen_string_literal: true

class Resident < ApplicationRecord
  has_one :address, dependent: :destroy

  has_one_attached :photo

  accepts_nested_attributes_for :address

  validates :full_name, presence: true
  validates :cpf, presence: true, uniqueness: true, cpf: true
  validates :cns, presence: true, uniqueness: true, cns: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :birth_date, presence: true, cns_birth_date: true
  validates :phone, presence: true, phone: true
  validates :photo, presence: true
  enum status: %i[inactive active]
  validates :status, inclusion: { in: Resident.statuses.keys }

  include PgSearch::Model
  pg_search_scope :search_by_full_name, against: [:full_name]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/residents_controller.rb
# frozen_string_literal: true

class ResidentsController < ApplicationController
  before_action :set_resident, only: %i[show edit update destroy]

  # GET /residents or /residents.json
  def index
    if params[:query].present?
      @residents = Resident.search_by_full_name(params[:query])
    else
      @residents = Resident.includes(:address).all
    end
  end

  # GET /residents/1 or /residents/1.json
  def show; end

  # GET /residents/new
  def new
    @resident = Resident.new
    @resident.build_address
  end

  # GET /residents/1/edit
  def edit; end

  # POST /residents or /residents.json
  def create
    @resident = Resident.new(resident_params)

    respond_to do |format|
      if @resident.save
        ResidentMailer.notify(@resident).deliver_now
        TwilioClient.new.send_text(@resident, 'Você foi cadastrado no sistema!')

        format.html { redirect_to resident_url(@resident), notice: 'Resident was successfully created.' }
        format.json { render :show, status: :created, location: @resident }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    @resident = Resident.find(params[:id])
    if @resident.update(resident_params)
      ResidentMailer.notify_status(@resident).deliver_now
      redirect_to residents_path, notice: 'Status atualizado com sucesso.'
    else
      redirect_to residents_path, alert: 'Falha ao atualizar o status.'
    end
  end

  # PATCH/PUT /residents/1 or /residents/1.json
  def update
    respond_to do |format|
      if @resident.update!(resident_params)
        format.html { redirect_to resident_url(@resident), notice: 'Resident was successfully updated.' }
        format.json { render :show, status: :ok, location: @resident }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_resident
    @resident = Resident.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def resident_params
    params.require(:resident).permit(
      :full_name,
      :cpf,
      :cns,
      :email,
      :birth_date,
      :phone,
      :photo,
      :status,
      address_attributes: %i[
        zip_code
        street
        complement
        neighborhood
        city
        state
        ibge_code
      ]
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/residents_helper.rb
# frozen_string_literal: true

module ResidentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ewerton</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/residents/_form.html.erb
<h1>New 1 resident</h1>

<%= form_for @resident do |form| %>
  <% if @resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
        <% @resident.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :cns %>
    <%= form.text_field :cns %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_field :birth_date, max: Date.today.strftime('%Y-%m-%d') %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, placeholder: "+5584999060981", data: {target: "hello.phone"}, action: "input->hello#mask" %>
    </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Resident.statuses.keys.to_a) %>
  </div>

  <div data-controller="hello">
  <%= form.fields_for :address do |address_form| %>
    <%= address_form.label :zip_code %> 
    <%= address_form.text_field :zip_code, data: { controller:'hello', action: 'input->hello#lookup', target:'zipcode' } %>
    <%= address_form.label :street  %>
    <%= address_form.text_field :street, data: {target: "hello.street"} %>
    
    <%= address_form.label :complement %>
    <%= address_form.text_field :complement, data: {target: "hello.complement"} %>
    
    <%= address_form.label :neighborhood %>
    <%= address_form.text_field :neighborhood, data: {target: "hello.neighborhood"} %>
    
    <%= address_form.label :city %>
    <%= address_form.text_field :city, data: {target: "hello.city"} %>
    
    <%= address_form.label :state %>
    <%= address_form.text_field :state, data: {target: "hello.state"} %>
    
    <%= address_form.label :ibge_code %>
    <%= address_form.text_field :ibge_code, data: {target: "hello.ibge_code"} %>
    </div>
    
  <% end %>  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to residents", residents_path %>
</div>

app/views/residents/_resident.html.erb
<div id="<%= dom_id resident %>">
</div>

app/views/residents/edit.html.erb
<h1>Editing resident</h1>

<%= render "form", resident: @resident %>

<br>

<div>
  <%= link_to "Show this resident", @resident %> |
  <%= link_to "Back to residents", residents_path %>
</div>

app/views/residents/index.html.erb
<h1>Residentes</h1>
<%= form_tag residents_path, method: :get do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search residents by full name" %>
  <%= submit_tag "Search" %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Nome completo</th>
      <th>CPF</th>
      <th>CNS</th>
      <th>Email</th>
      <th>Data de nascimento</th>
      <th>Celular</th>
      <th>Status</th>
      <th>Foto</th>
      <th>CEP</th>
      <th>Rua</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>UF</th>
      <th>Complemento</th>
    </tr>
  </thead>
  <tbody>
    <% @residents.each do |resident| %>
      <tr>
        <td><%= resident.full_name %></td>
        <td><%= resident.cpf %></td>
        <td><%= resident.cns %></td>
        <td><%= resident.email %></td>
        <td><%= resident.birth_date&.strftime("%d/%m/%Y") %></td>
        <td><%= resident.phone %></td>
        <td>
        <%= form_with model: resident, url: update_status_resident_path(resident), method: :patch do |f| %>
          <%= f.select :status, options_for_select(["active", "inactive"], resident.status), class: "status-select" %>
          <%= f.submit "Atualizar", class: "update-status-button" %>
        <% end %>
      </td>
        <td>
          <% if resident.photo.attached? %>
            <%= image_tag(resident.photo, style: "height:50px") %>
          <% end %>
        </td>
        <% if resident.address %>
          <td><%= resident.address.zip_code %></td>
          <td><%= resident.address.street %></td>
          <td><%= resident.address.neighborhood %></td>
          <td><%= resident.address.city %></td>
          <td><%= resident.address.state %></td>
          <td><%= resident.address.complement %></td>
        <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/residents/new.html.erb
<%= render "form", resident: @resident %>

app/views/residents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @resident %>

<div>
  <%= link_to "Edit this resident", edit_resident_path(@resident) %> |
  <%= link_to "Back to residents", residents_path %>

  <%= button_to "Destroy this resident", @resident, method: :delete %>
</div>